// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import DarkModeToggle from "@/components/dark_mode_toggle"; // new client component
import Footer from "@/components/footer";
export const metadata: Metadata = {
  title: "MemoTag",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="[font-family:sans-serif] antialiased relative">
        <Navbar />
        <main className="h-screen overflow-y-scroll">{children}</main>
        <Footer />
        <DarkModeToggle />
      </body>
    </html>
  );
}
